# DEPRECATED: This root chart is deprecated in favor of cloud-specific overlay charts.
#
# Please use the new chart structure:
#   - charts/hyperfleet-gcp/  - For GCP deployments (GKE, Pub/Sub, Workload Identity)
#   - charts/hyperfleet-aws/  - For AWS deployments (coming soon)
#   - charts/hyperfleet-azure/ - For Azure deployments (coming soon)
#
# Migration:
#   OLD: helm install hyperfleet . -f values.yaml
#   NEW: helm install hyperfleet charts/hyperfleet-gcp -f examples/gcp-pubsub/values.yaml
#
# See README.md for full migration guide.

apiVersion: v2
name: hyperfleet
description: "[DEPRECATED] HyperFleet Platform - Use charts/hyperfleet-gcp instead"
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: HyperFleet Team
    email: hyperfleet-team@redhat.com
keywords:
  - hyperfleet
  - kubernetes
  - cluster-management
  - multi-cloud
home: https://github.com/openshift-hyperfleet/hyperfleet-chart

dependencies:
  # HyperFleet API - Cluster lifecycle management REST API
  - name: hyperfleet-api
    version: "1.0.0"
    repository: "git+https://github.com/openshift-hyperfleet/hyperfleet-api@charts?ref=main"
    condition: hyperfleet-api.enabled

  # HyperFleet Sentinel - Resource polling and event publishing
  - name: sentinel
    version: "0.1.0"
    repository: "git+https://github.com/openshift-hyperfleet/hyperfleet-sentinel@deployments/helm/sentinel?ref=main"
    condition: sentinel.enabled

  # Adapter: Landing Zone - Creates cluster namespaces
  - name: landing-zone
    version: "1.0.0"
    repository: "git+https://github.com/openshift-hyperfleet/adapter-landing-zone@charts?ref=main"
    alias: adapter-landing-zone
    condition: adapter-landing-zone.enabled

  # Adapter: Validation GCP - Validates cluster resources on GCP
  - name: validation-gcp
    version: "1.0.0"
    repository: "git+https://github.com/openshift-hyperfleet/adapter-validation-gcp@charts?ref=main"
    condition: validation-gcp.enabled
